name: autoyolo
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.10.18
  - pip
  - numpy
  - pillow
  - opencv
  - scipy
  - pip:
      - ultralytics==8.3.34
      - PySide6==6.7.2
      - qdarktheme==2.1.0
      - torch==2.5.1
      - torchvision==0.20.1
      - torchaudio==2.5.1
      - torch-directml>=0.2.0
      - onnxruntime==1.18.1
      - loguru==0.7.2
